spring:
  application:
    name: training-web
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/training_web
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8080
